[project]
name = "code"
version = "0.1.0"
description = "Projet d'IQRO"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "qiskit>=2.3.0",
    "qiskit-aer>=0.4",
    "scipy>=1.10",
    "pandas>=2.0",
    "matplotlib>=3.7",
    "seaborn>=0.12",
]
